In [176]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from copy import deepcopy
import math
import random

## Numerical computing with NumPy

In [142]:
a = np.arange(8, dtype=float)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [143]:
%timeit np.sqrt(2.5)

363 ns ± 1.73 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [144]:
%timeit math.sqrt(2.5)

24.5 ns ± 0.0277 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [145]:
b = np.array([a, a * 2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [146]:
print(b.sum(axis=0))
print(b.sum(axis=1))

[ 0.  3.  6.  9. 12. 15. 18. 21.]
[28. 56.]


In [147]:
c = np.zeros((2, 3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [148]:
c = np.ones((2, 3, 4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [149]:
d = np.zeros_like(c, dtype='f8', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [150]:
d = np.ones_like(c, dtype='f8', order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [151]:
e = np.empty((2, 3, 2))
e

array([[[0.0078125, 0.0078125],
        [0.0078125, 0.0078125],
        [0.0078125, 0.0078125]],

       [[0.0078125, 0.0078125],
        [0.0078125, 0.0078125],
        [0.0078125, 0.0078125]]])

In [152]:
f = np.empty_like(c)
f

array([[[1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216]],

       [[1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216]]], dtype=int32)

In [153]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [154]:
g = np.linspace(5, 15, 10)
g

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [155]:
g.dtype

dtype('float64')

In [156]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [157]:
h = g.reshape((3, 5))
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [158]:
h.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [159]:
x = np.arange(5)
np.resize(x, (10, 2))

array([[0, 1],
       [2, 3],
       [4, 0],
       [1, 2],
       [3, 4],
       [0, 1],
       [2, 3],
       [4, 0],
       [1, 2],
       [3, 4]])

In [160]:
h = h.T
h

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [161]:
np.hstack((h, h * 2))

array([[ 0,  5, 10,  0, 10, 20],
       [ 1,  6, 11,  2, 12, 22],
       [ 2,  7, 12,  4, 14, 24],
       [ 3,  8, 13,  6, 16, 26],
       [ 4,  9, 14,  8, 18, 28]])

In [162]:
np.vstack((h, h * 0.5))

array([[ 0. ,  5. , 10. ],
       [ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8. , 13. ],
       [ 4. ,  9. , 14. ],
       [ 0. ,  2.5,  5. ],
       [ 0.5,  3. ,  5.5],
       [ 1. ,  3.5,  6. ],
       [ 1.5,  4. ,  6.5],
       [ 2. ,  4.5,  7. ]])

In [163]:
h.flatten()

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [164]:
for i in h.flat:
    print(i, end=',')

0,5,10,1,6,11,2,7,12,3,8,13,4,9,14,

In [166]:
h

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [171]:
h > 8

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False,  True,  True]])

In [169]:
(h > 4) & (h <= 12)

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [False,  True, False],
       [False,  True, False]])

In [172]:
h[(h > 4) & (h <= 12)]

array([ 5, 10,  6, 11,  7, 12,  8,  9])

In [174]:
np.where(h % 2 == 0, 'Even', 'Odd')

array([['Even', 'Odd', 'Even'],
       ['Odd', 'Even', 'Odd'],
       ['Even', 'Odd', 'Even'],
       ['Odd', 'Even', 'Odd'],
       ['Even', 'Odd', 'Even']], dtype='<U4')

In [175]:
np.where(h <= 7, h * 2, h / 2)

array([[ 0. , 10. ,  5. ],
       [ 2. , 12. ,  5.5],
       [ 4. , 14. ,  6. ],
       [ 6. ,  4. ,  6.5],
       [ 8. ,  4.5,  7. ]])

In [177]:
I = 5000